// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/daichi1002/order-management-system/backend/internal/adapter/handler"
	"github.com/daichi1002/order-management-system/backend/internal/adapter/repository"
	"github.com/daichi1002/order-management-system/backend/internal/usecase"
	"github.com/labstack/echo/v4"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer(db *gorm.DB) (*echo.Echo, error) {
	menuRepository := repository.NewMenuRepository(db)
	menuUsecase := usecase.NewMenuUsecase(menuRepository)
	menuHandler := handler.NewMenuHandler(menuUsecase)
	echoEcho := newServer(menuHandler)
	return echoEcho, nil
}

// wire.go:

func newServer(menuHandler *handler.MenuHandler) *echo.Echo {
	e := echo.New()
	e.GET("/menus", menuHandler.GetAllMenus)
	return e
}
