coverage:
  if: true
  paths:
    - ./backend/coverage.out
codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "!**/mock_**.go"
  test:
    - "**/*_test.go"
testExecutionTime:
  if: true
comment:
  if: is_pull_request
  hideFooterLink: false
  deletePrevious: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
