services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: order-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

volumes:
  postgres_data:
