package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"strconv"
	"time"

	"github.com/daichi1002/order-management-system/backend/internal/adapter/graph/generated"
	"github.com/daichi1002/order-management-system/backend/internal/adapter/graph/scalar"
	"github.com/daichi1002/order-management-system/backend/internal/domain/model"
	"github.com/daichi1002/order-management-system/backend/internal/infrastructure/logger"
	"go.uber.org/zap"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input generated.OrderInput) (string, error) {
	order, err := model.NewOrder(input.TicketNumber, time.Time(input.CreatedAt), input.TotalAmount)
	if err != nil {
		return "", err
	}

	var orderItems []*model.OrderItem
	for _, o := range input.Items {
		item, err := model.NewOrderItem(o.Menu.ID, o.Quantity, o.Price)
		if err != nil {
			return "", err
		}
		orderItems = append(orderItems, item)
	}
	id, err := r.orderUsecase.CreateOrder(ctx, order, orderItems)

	if err != nil {
		logger.Error("server error", zap.Error(err))
		return "", err
	}

	return strconv.Itoa(id), nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, id string) (bool, error) {
	orderId, err := strconv.Atoi(id)

	if err != nil {
		return false, err
	}

	err = r.orderUsecase.CancelOrder(ctx, orderId)

	if err != nil {
		logger.Error("server error", zap.Error(err))
		return false, err
	}

	return true, nil
}

// CreateDailyClosing is the resolver for the createDailyClosing field.
func (r *mutationResolver) CreateDailyClosing(ctx context.Context, input *generated.DailyClosingInput) (bool, error) {
	dailyClosing, err := model.NewDailyClosing(time.Time(input.ClosingDate), input.TotalSales, input.TotalOrders)

	if err != nil {
		return false, err
	}

	err = r.dailyClosingUsecase.CreateDailyClosings(ctx, *dailyClosing)

	if err != nil {
		logger.Error("server error", zap.Error(err))
		return false, err
	}

	return true, nil
}

// GetMenus is the resolver for the getMenus field.
func (r *queryResolver) GetMenus(ctx context.Context) ([]*generated.Menu, error) {
	menus, err := r.menuUsecase.GetMenus(ctx)

	if err != nil {
		logger.Error("server error", zap.Error(err))
		return nil, err
	}

	var response []*generated.Menu
	for _, menu := range menus {
		response = append(response, &generated.Menu{
			ID:    strconv.Itoa(menu.Id),
			Name:  menu.Name,
			Price: menu.Price,
		})
	}
	return response, nil
}

// GetOrders is the resolver for the getOrders field.
func (r *queryResolver) GetOrders(ctx context.Context) ([]*generated.Order, error) {
	orders, err := r.orderUsecase.GetOrders(ctx)

	if err != nil {
		logger.Error("server error", zap.Error(err))
		return nil, err
	}

	return orders, nil
}

// IsSalesConfirmed is the resolver for the isSalesConfirmed field.
func (r *queryResolver) IsSalesConfirmed(ctx context.Context, date scalar.DateTime) (bool, error) {
	isConfirmed, err := r.dailyClosingUsecase.IsSalesConfirmed(ctx, time.Time(date))

	if err != nil {
		logger.Error("server error", zap.Error(err))
	}

	return isConfirmed, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
