name: test

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
      - staging
      - develop
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Run tests with coverage output
        run: go test -cover -coverprofile=coverage.out `go list ./... | grep -v "\.gen\.go" | grep -v "mock_.*\.go" | grep -v "generated\.go"`

      - name: Coverage report comment
        if: always()
        uses: k1LoW/octocov-action@v0

